services:
  # 1. Database Service
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: online_retail
    ports:
      - "5432:5432"
    networks:
      - pipeline-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d online_retail"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Management Tool
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8085:80"
    depends_on:
      - postgres-db
    networks:
      - pipeline-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json  # ✅ auto-loads server config
    

  # 3. Your Python Pipeline
  feeder:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: data-feeder
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - pipeline-network
    environment:
      - PYTHONUNBUFFERED=1
    # Mount the local file into the container's /app directory
    volumes:
      - ./online_retail_II.xlsx:/app/online_retail_II.xlsx:ro
    command: >
      --pg_host postgres-db
      --pg_user root
      --pg_pass root
      --pg_db online_retail
      --chunksize 10000

networks:
  pipeline-network:
    driver: bridge

volumes:          # ← add this
  pgadmin-data: